### ISSUE TITLE
Ошибка с названием и описанием квестов

### ISSUE THREAD

**Issue by ivansenpaii** [cyber01/ddss_locale#2]
После обновления 7.4 сбились названия и описания квестов

**Comment by ivansenpaii** [comment]
![image](https://user-images.githubusercontent.com/65483938/82138739-eb400800-984c-11ea-9415-d0c3045fbf1d.png)
![image](https://user-images.githubusercontent.com/65483938/82138746-f5fa9d00-984c-11ea-8de2-7102fcd768a5.png)
![image](https://user-images.githubusercontent.com/65483938/82138751-001c9b80-984d-11ea-8bc6-a57d95262758.png)
Это часть ошибок, присутствуют и другие

**Comment by cyber01** [comment]
В 7.4 были сдвинуты на 1 ID почти у всех квестов. Сейчас проверил - согласно файлу квестов квест с черным лотосом имеет ID 313, описание к 313 соответствует (черный лотос). 

Команда /bq_admin default load выполнялась после обновления?

**Comment by ivansenpaii** [comment]
Действительно, после выполнения команды все на своих местах
